### ISSUE TITLE
Activity has leaked window

### ISSUE THREAD

**Issue by godjoy** [mash-up-kr/Potato-Invitation-Android#73]
E/WindowManager: android.view.WindowLeaked: Activity com.mashup.nawainvitation.presentation.main.MainActivity has leaked window DecorView@14d720[MainActivity] that was originally added here
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:728)
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:712)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:399)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:109)
        at android.app.Dialog.show(Dialog.java:340)
        at com.mashup.nawainvitation.presentation.main.MainActivity.showLoading(MainActivity.kt:123)
        at com.mashup.nawainvitation.presentation.main.MainViewModel$loadInvitations$1.onLoading(MainViewModel.kt:70)
        at com.mashup.nawainvitation.data.repository.InvitationRepositoryImpl$getInvitations$1.accept(InvitationRepositoryImpl.kt:26)
        at com.mashup.nawainvitation.data.repository.InvitationRepositoryImpl$getInvitations$1.accept(InvitationRepositoryImpl.kt:15)
        at io.reactivex.internal.operators.single.SingleDoOnSubscribe$DoOnSubscribeSingleObserver.onSubscribe(SingleDoOnSubscribe.java:60)
        at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.onSubscribe(SingleObserveOn.java:57)
        at io.reactivex.internal.operators.observable.ObservableSingleSingle$SingleElementObserver.onSubscribe(ObservableSingleSingle.java:58)
        at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onSubscribe(BodyObservable.java:48)
        at retrofit2.adapter.rxjava2.CallEnqueueObservable.subscribeActual(CallEnqueueObservable.java:40)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.internal.operators.single.SingleObserveOn.subscribeActual(SingleObserveOn.java:35)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.internal.operators.single.SingleDoOnSubscribe.subscribeActual(SingleDoOnSubscribe.java:41)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.internal.operators.single.SingleDoOnTerminate.subscribeActual(SingleDoOnTerminate.java:37)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.Single.subscribe(Single.java:3652)
        at com.mashup.nawainvitation.data.repository.InvitationRepositoryImpl.getInvitations(InvitationRepositoryImpl.kt:31)
        at com.mashup.nawainvitation.presentation.main.MainViewModel.loadInvitations(MainViewModel.kt:51)
        at com.mashup.nawainvitation.presentation.main.MainFragment.onViewCreated(MainFragment.kt:30)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:332)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2641)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2589)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
E/WindowManager:     at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
        at android.app.Activity.performStart(Activity.java:8008)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3382)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2049)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)

**Comment by dlwls5201** [comment]
제가 수정하겠습니다.
